name: Sonar

on:
  push:
    branches: [ develop ]

jobs:
  compile-verify:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.14
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: poetry install

      - name: Run tests with coverage
        run: poetry run pytest

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@ba9859eae8dd6bd29e412f25ddbbef3d032000f4
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_URI }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}